# Site settings
name: Raiyan Hossain
title: Raiyan Hossain | Undergraduate Student
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://raiyanh717.github.io/
baseurl: ''
email: r17hossain@gmail.com
#resume: https://bchiang7.github.io/resume.pdf
logo: https://raiyanh717.github.io/img/domain.ico
social:
  - title: resume
    url: https://docs.google.com/document/d/1cT8ynwUV-9VBgzOhrnfe4leLEc17mS8G9bgoUkaVG8U/preview
  - title: github
    url: https://github.com/raiyanh717
  - title: linkedin
    url: https://www.linkedin.com/in/raiyan-hossain-/
  - title: email
    url: mailto:r17hossain@gmail.com
  - title: instagram
    url: https://instagram.com/raiyan_hossain14

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
